# SITE CONFIGURATION
baseurl: ""
url: "https://givenone.me"

# THEME-SPECIFIC CONFIGURATION
title: givenone                                    # site's title
description: "준원 소프트웨어 연구소"      # used by search engines
avatar: assets/img/junwon_square.png                         # Empty for no avatar in navbar
favicon: assets/JW.ico                             # Icon displayed in the tab

# Header and footer text
header_text: 준원 소프트웨어 연구소  # Change Blog header text
header_feature_image: assets/img/pexels/triangular.jpeg
footer_text: >
  © 2020 <b>Seo Junwon</b> <br> @ <a href="https://cse.snu.ac.kr/">SNU CSE</a>

# Blog
excerpt: true                                           # Or "truncate" (first 250 characters), "false" to disable
post_navigation: true
color_image: /assets/img/lineart.png                    # A bit transparent for color posts.

# Features
katex: true                                             # Enable if using math markup
google_analytics: UA-173050167-1                        # Tracking ID, e.g. "UA-000000-01"
cookie_consent: true                                   # To respect the usage of cookies
disqus_shortname: givenone                                      # Your discus shortname for comments
layout_variables:                                       # Open the "_sass > base" folder, and open "_variables.scss"
footer_icons:                                           # In _data/social.yml
share_buttons:                                          # In _data/social.yml
authors:                                                # In _data/authors.yml
language:                                               # In _data/language.yml

# PAGINATION
paginate: 5
paginate_path: "/blog/page:num"

# PORTFOLIO
collections:
  portfolio:
    output: true
    permalink: /works/:name
  writings:
    output: true
    permalink: /post/:name

# BUILD SETTINGS
plugins: [jekyll-paginate, jekyll-seo-tag, jekyll-feed, jekyll-sitemap] # , 
exclude: [".jekyll-cache", ".idea", "vendor/*", "assets/node_modules"]

# theme: type-on-strap                                  # if using the theme as a jekyll theme gem
remote_theme: sylhare/Type-on-Strap                     # If using as a remote_theme in github
